# Week 1 Exercises

In [1]:
import numpy as np

### Ex 1.1

In [2]:
def homogeneous_2_inhomogeneous(p: np.ndarray) -> np.ndarray:
    '''
    Drop the last coordinate and divide the other coords with it
    '''
    return p[:-1] / p[-1]

p1 = np.array([1, 2, 1])
p2 = np.array([4, 2, 2])
p3 = np.array([6, 4, -1])
p4 = np.array([5, 3, 0.5])

print(homogeneous_2_inhomogeneous(p1))
print(homogeneous_2_inhomogeneous(p2))
print(homogeneous_2_inhomogeneous(p3))
print(homogeneous_2_inhomogeneous(p4))

[1. 2.]
[2. 1.]
[-6. -4.]
[10.  6.]


### Ex 1.2

In [3]:
P1 = np.array([1, 10, -3, 1])
P2 = np.array([2, -4, 1.1, 2])
P3 = np.array([0, 0, -1, 10])
P4 = np.array([-15, 3, 6, 3])

print(homogeneous_2_inhomogeneous(P1))
print(homogeneous_2_inhomogeneous(P2))
print(homogeneous_2_inhomogeneous(P3))
print(homogeneous_2_inhomogeneous(P4))

[ 1. 10. -3.]
[ 1.   -2.    0.55]
[ 0.   0.  -0.1]
[-5.  1.  2.]


### Ex 1.3

In [4]:
import sympy as sp
s, x, y = sp.symbols('s x y')
p_h = np.array([s*x, s*y, s])

# From x + 2y = 3
a = 1
b = 2
c = -3

l = np.array([a, b, c])

### Ex 1.4

In [5]:
p1 = np.array([3, 0, 1])
p2 = np.array([6, 0, 2])
p3 = np.array([1, 1, 2])
p4 = np.array([1, 1, 1])
p5 = np.array([110, -40, 10])
p6 = np.array([11, 4, 1])

print(p1 @ l, p2 @ l, p3 @ l, p4 @ l, p5 @ l, p6 @ l)

0 0 -3 0 0 16


Points p1, p2, p4, and p5 are on the line

### Ex 1.5

In [6]:
l0 = np.array([1, 1, -1])
l1 = np.array([-1, 1, -3])
q_I = np.cross(l0, l1)
print(q_I)

[-2  4  2]


### Ex 1.6

In [11]:
p1, p2, p3 = sp.symbols('p1 p2 p3')
q1, q2, q3 = sp.symbols('q1 q2 q3')
p = np.array([p1, p2, p3])
q = np.array([q1, q2, q3])

A = np.array([
    [10, 0, 2], 
    [0, 10, -3],
    [0, 0, 1]
])

print(f"{A @ p} = {q}")

[10*p1 + 2*p3 10*p2 - 3*p3 p3] = [q1 q2 q3]


### Ex 1.7

In [ ]:
from numpy.linalg import norm

l = np.array([
    1/np.sqrt(2),
    1/np.sqrt(2),
    -1
])

p1 = np.array([0, 0, 1])
p2 = np.array([np.sqrt(2), np.sqrt(2), 1])
p3 = np.array([np.sqrt(2), np.sqrt(2), 4])



2.23606797749979 2.23606797749979 5.0990195135927845
